require("rawnvim.option")
require("rawnvim.osKeyMap").setup()
require("rawnvim.keymap")
require("rawnvim.plugin")
require("rawnvim.colorscheme")
require("rawnvim.lsp")
require("rawnvim.pluginConfig.completion")
require("rawnvim.pluginConfig.telescope")
require("rawnvim.pluginConfig.treesitter")
require("rawnvim.pluginConfig.vgit")
require("rawnvim.pluginConfig.lazygit")
require("rawnvim.pluginConfig.barbar")
require("rawnvim.pluginConfig.nerdTree")
require("rawnvim.pluginConfig.nullLs")
require("rawnvim.pluginConfig.motion")
require("rawnvim.pluginConfig.vimcalc3")

-- vim.lsp.set_log_level("debug")
