require("hexide.nvim.option")
require("hexide.nvim.osKeyMap").setup()
require("hexide.nvim.keymap")
require("hexide.nvim.plugin")
require("hexide.nvim.colorscheme")
require("hexide.nvim.lsp")
require("hexide.nvim.pluginConfig.completion")
require("hexide.nvim.pluginConfig.telescope")
require("hexide.nvim.pluginConfig.treesitter")
require("hexide.nvim.pluginConfig.vgit")
require("hexide.nvim.pluginConfig.lazygit")
require("hexide.nvim.pluginConfig.barbar")
require("hexide.nvim.pluginConfig.nerdTree")
require("hexide.nvim.pluginConfig.nullLs")
require("hexide.nvim.pluginConfig.motion")
require("hexide.nvim.pluginConfig.spectre")
require("hexide.nvim.pluginConfig.fidget")

-- vim.lsp.set_log_level("debug")
